### ISSUE TITLE
http methods

### ISSUE THREAD

**Issue by Betank** [jkyberneees/fastify-gateway#18]
It would be nice to also have the possibility to define http methods for routes, like

```
{
    prefix: '/public',
    prefixRewrite: '',
    target: 'http://localhost:3000',
    methods: ['GET']
  }
```

**Comment by jkyberneees** [comment]
Thanks once more @Betank for your collaboration here. The feature just landed in https://github.com/jkyberneees/fastify-gateway/releases/tag/v2.1.0

Regards
