### ISSUE TITLE
Path parameters? 

### ISSUE THREAD

**Issue by parthibd** [jkyberneees/fastify-gateway#21]
Thank you for this amazing library. I have two concerns. First is how do I map a path of my gateway to a totally different prefix in my service. Second, how do I specify path parameters?

**Comment by jkyberneees** [comment]
Hi @parthibd thanks for your kind words. Can you describe with an example what exactly would you like to have?

Thanks.

**Comment by parthibd** [comment]
Say my urls are not mapped exactly to the services endpoints. If I pass a path param eg: /user/1/details, and my service endpoint is userdetails/:id. How do I map 1 to the :id?

**Comment by jkyberneees** [comment]
I will get back to you with an example ASAP.

**Comment by parthibd** [comment]
Thanks a lot for the prompt reply . :)

**Comment by jkyberneees** [comment]
Hi @parthibd, you can find an example for this use case here:
https://github.com/jkyberneees/fastify-gateway/blob/master/demos/endpoint-proxy.js

Please consider to update the gateway to latest version:
https://github.com/jkyberneees/fastify-gateway/releases/tag/v2.2.0

**Comment by parthibd** [comment]
Thanks a lot. Exactly what I was looking for. :)
