### ISSUE TITLE
Trailing slash problem

### ISSUE THREAD

**Issue by parthibd** [jkyberneees/fastify-gateway#23]
When the trailing slash is present in my url , it works fine . The moment its gone ,404 . Possible bug ?

**Comment by jkyberneees** [comment]
In case you want to route endpoints instead of fully proxy to remote APIs, you can define your route as described:
```js
{
      pathRegex: '',
      prefix: '/endpoint-proxy',
      prefixRewrite: '/endpoint-proxy',
      target: 'http://localhost:3000',
      middlewares: [],
      hooks: {
      }
}
```

See how **pathRegex** is disabled here.

Regards.

**Comment by parthibd** [comment]
Thanks for the heads up. I was thinking if I should make a pull request adding a global routeRegex that will be overridden if a route defines its own routeRegex?

**Comment by jkyberneees** [comment]
Hi @parthibd, global `pathRegex` is allowed from v2.3.0.
I will close this issue accordingly.

Thanks.
