### ISSUE TITLE
Proxying requests to a domain with a subdirectory 

### ISSUE THREAD

**Issue by parthibd** [jkyberneees/fastify-gateway#27]
When I proxy requests to a domain eg: `http://localhost/mydir` it returns a 404. Is there anything I'm doing wrong? In this case my prefix is `myproxy`.

**Comment by jkyberneees** [comment]
Hi @parthibd, please consider that `/mydir` is not part of your domain, it is actually part of your prefix.
Can you try again considering that hint.

Regards
