### ISSUE TITLE
what is shouldAbortProxy in the proxy function ?

### ISSUE THREAD

**Issue by matth-c3** [jkyberneees/fastify-gateway#28]
Hello, 

what is the purpose of 'shouldAbortProxy' in : 

https://github.com/jkyberneees/fastify-gateway/blob/master/index.js#L6-L8 ? 

Thanks

**Comment by jkyberneees** [comment]
hi @matth-c3, as described: 
```js 
async onRequest (req, reply) {
      //   // we can optionally reply from here if required
      //   reply.send('Hello World!')
      //
      //   return true // truthy value returned will abort the request forwarding
},
```

The `shouldAbortProxy` holds the result of the onRequest hook execution, it allows developers to completely abort the request forwarding at gateway level.

Use cases:
- cache
- aggregations
- validation
- ...
